version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: chalk
    versions:
    - 4.1.0
